DataPoliceUk.AzureMapsWebsite/Models/ErrorViewModel.cs
using System;

namespace DataPoliceUk.AzureMapsWebsite.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DataPoliceUk.AzureMapsWebsite/Controllers/ForcesController.cs
using Microsoft.AspNetCore.Mvc;

namespace DataPoliceUk.AzureMapsWebsite.Controllers
{
    public class ForcesController : Controller
    {
        public IActionResult Index()
        {
            ViewData["Message"] = "Forces description page.";

            return View();
        }
    }
}

DataPoliceUk.AzureMapsWebsite/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using DataPoliceUk.AzureMapsWebsite.Models;

namespace DataPoliceUk.AzureMapsWebsite.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DataPoliceUk.AzureMapsWebsite/Controllers/StreetCrimesController.cs
using Microsoft.AspNetCore.Mvc;

namespace DataPoliceUk.AzureMapsWebsite.Controllers
{
    public class StreetCrimesController : Controller
    {
        public IActionResult Index()
        {
            ViewData["Message"] = "Street Crimes description page.";

            return View();
        }
    }
}

DataPoliceUk.AzureMapsWebsite/Views/Forces/Index.cshtml
@{
    ViewData["Title"] = "Forces";
}

<div class="row forces">
    <div class="col-md-12">
        <h2>@ViewData["Title"]</h2>
        <h5>@ViewData["Message"]</h5>
    </div>
    <div class="col-md-12">
        <div class="row">
            <div class="col-11">
                <select id="forces" class="forces__select form-control">
                    <option value="">Please select...</option>
                </select>
            </div>
            <div class="col-1">
                <div class="spinner-border spinner-border-sm text-success" role="status" style="display:none;">
                    <span class="sr-only">Loading...</span>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <div class="card bg-light mb-3 force__panel" style="display:none;">
                    <div class="card-body">
                        <h5 class="card-title force__name"></h5>
                        <p class="card-text force__description"></p>
                        <p>Telephone: <span class="force__telephone"></span></p>
                        <p>Url: <a href="" target='_blank' class="card-link force__url"></a></p>
                    </div>
                </div>
            </div>            
        </div>

        <div class="row force__repeater" style="display:none;"></div>

    </div>
</div>

DataPoliceUk.AzureMapsWebsite/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="carousel-item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

DataPoliceUk.AzureMapsWebsite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DataPoliceUk.AzureMapsWebsite</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    @*<nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">DataPoliceUk.AzureMapsWebsite</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Forces" asp-action="Index">Forces</a></li>
                    <li><a asp-area="" asp-controller="StreetCrimes" asp-action="Index">Street Crimes</a></li>
                </ul>
            </div>
        </div>
    </nav>*@

    <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">DataPoliceUk.AzureMapsWebsite</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item"><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li class="nav-item"><a asp-area="" asp-controller="Forces" asp-action="Index">Forces</a></li>
                    <li class="nav-item"><a asp-area="" asp-controller="StreetCrimes" asp-action="Index">Street Crimes</a></li>
                </ul>
            </div>
        </div>        
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container">
        @RenderBody()

        <div class="row">
            <div class="col-12">
                <hr />
                <footer>
                    <p>&copy; 2019 - DataPoliceUk.AzureMapsWebsite</p>
                </footer>
            </div>
        </div>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

DataPoliceUk.AzureMapsWebsite/Views/StreetCrimes/Index.cshtml
@{
    ViewData["Title"] = "Street Crimes";
}

<link rel="stylesheet" href="https://atlas.microsoft.com/sdk/css/atlas.min.css?api-version=2" type="text/css" />
<script src="https://atlas.microsoft.com/sdk/js/atlas.min.js?api-version=2"></script>

<div class="row streetcrime">
    <div class="col-md-12">
        <h2>@ViewData["Title"]</h2>
        <h5>@ViewData["Message"]</h5>
    </div>
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-6">
                <select id="forces" class="streetcrime_forces__select form-control">
                    <option value="">Please select...</option>
                </select>
            </div>
            <div class="col-md-5">
                <select id="boundary" class="streetcrime_boundary__select form-control">
                    <option value="">Please select...</option>
                </select>
            </div>
            <div class="col-1">
                <div class="spinner-border spinner-border-sm text-success" role="status" style="display:none;">
                    <span class="sr-only">Loading...</span>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <h5>Filters:</h5>
        <form class="form-inline">
            <div class="form-group mb-2">
                <label for="date" class="sr-only">Date</label>
                <select id="date" class="form-control">
                    <option value="">Select a date...</option>
                    <option value="2019-04">2019-04</option>
                    <option value="2019-03">2019-03</option>
                    <option value="2019-02">2019-02</option>
                    <option value="2019-01">2019-01</option>
                    <option value="2018-12">2018-12</option>
                    <option value="2018-11">2018-11</option>
                    <option value="2018-10">2018-10</option>
                    <option value="2018-09">2018-09</option>
                    <option value="2018-08">2018-08</option>
                    <option value="2018-07">2018-07</option>
                    <option value="2018-06">2018-06</option>
                    <option value="2018-05">2018-05</option>
                    <option value="2018-04">2018-04</option>
                    <option value="2018-03">2018-03</option>
                    <option value="2018-02">2018-02</option>
                    <option value="2018-01">2018-01</option>
                </select>
            </div>
            <div class="form-group mx-sm-3 mb-2">
                <label for="latitude" class="sr-only">Latitude</label>
                <input type="text" id="latitude" class="form-control" placeholder="latitude" disabled />
            </div>
            <div class="form-group mb-2">
                <label for="longitude" class="sr-only">Longitude</label>
                <input type="text" id="longitude" class="form-control" placeholder="longitude" disabled />
            </div>
            <button type="submit" class="streetcrimes_btn btn btn-success mx-sm-3 mb-4" disabled>Submit</button>
        </form>
    </div>

    <div class="col-md-12">
        <div style="width: 100%;height: 600px">
            <div id="map"></div>
        </div>
    </div>
    <div class="col-md-12">
        <div id="legend">
            <h5>Legend</h5>
            <span class="badge badge-primary anti-social-behaviour">Anti Social Behaviour</span>
            <span class="badge badge-primary bicycle-theft">Bicycle Theft</span>
            <span class="badge badge-primary burglary">Burglary</span>
            <span class="badge badge-primary criminal-damage-arson">Criminal Damage Arson</span>
            <span class="badge badge-primary drugs">Drugs</span>
            <span class="badge badge-primary other-theft">Other Theft</span>
            <span class="badge badge-primary robbery">Robbery</span>
            <span class="badge badge-primary shoplifting">Shoplifting</span>
            <span class="badge badge-primary violent-crime">Violent Crime</span>
            <span class="badge badge-primary other-crime">Other Crime</span>
            <span class="badge badge-primary theft-from-the-person">Theft From The Person</span>
            <span class="badge badge-primary vehicle-crime">Vehicle Crime</span>
        </div>
    </div>
    
</div>

<style>
    #map {
        width: 100%;
        height: 100%;
    }
</style>